# Use the official Nginx image as the base mage
FROM nginx:1.21.3

# Copy your custom Nginx configuration file into the container
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Expose the port(s) that your Nginx server will listen on
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]

